-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Latte.

module Latte.AbsLatte where

import Prelude (Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type Program = Program' BNFC'Position
data Program' a = Prog a [TopDef' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type TopDef = TopDef' BNFC'Position
data TopDef' a
    = FnDef a (Type' a) Ident [Arg' a] (Block' a)
    | ClassDef a Ident [Field' a]
    | ClassExt a Ident Ident [Field' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Field = Field' BNFC'Position
data Field' a
    = AttrDef a (Type' a) Ident
    | MethodDef a (Type' a) Ident [Arg' a] (Block' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Arg = Arg' BNFC'Position
data Arg' a = Ar a (Type' a) Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Stmt = Stmt' BNFC'Position
data Stmt' a
    = Empty a
    | Exp a (Expr' a)
    | Ass a (Expr' a) (Expr' a)
    | Incr a (Expr' a)
    | Decr a (Expr' a)
    | Ret a (Expr' a)
    | VRet a
    | If a (Expr' a) (Stmt' a)
    | IfElse a (Expr' a) (Stmt' a) (Stmt' a)
    | While a (Expr' a) (Stmt' a)
    | For a (Type' a) Ident (Expr' a) (Stmt' a)
    | BStmt a (Block' a)
    | Decl a (Type' a) [Item' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Block = Block' BNFC'Position
data Block' a = Blck a [Stmt' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Item = Item' BNFC'Position
data Item' a = NoInit a Ident | Init a Ident (Expr' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Type = Type' BNFC'Position
data Type' a
    = Int a
    | Str a
    | Bool a
    | Void a
    | Array a (Type' a)
    | Class a Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Expr = Expr' BNFC'Position
data Expr' a
    = EOr a (Expr' a) (Expr' a)
    | EAnd a (Expr' a) (Expr' a)
    | ERel a (Expr' a) (RelOp' a) (Expr' a)
    | EAdd a (Expr' a) (AddOp' a) (Expr' a)
    | EMul a (Expr' a) (MulOp' a) (Expr' a)
    | Not a (Expr' a)
    | Neg a (Expr' a)
    | EClass a Ident
    | EAttr a (Expr' a) Ident
    | EMethod a (Expr' a) Ident [Expr' a]
    | EArr a (Type' a) (Expr' a)
    | EElem a (Expr' a) (Expr' a)
    | ESelf a
    | ENull a
    | ENullCast a (Type' a)
    | ENullClss a (Expr' a)
    | EVar a Ident
    | EInt a Integer
    | EString a String
    | ETrue a
    | EFalse a
    | EApp a Ident [Expr' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type AddOp = AddOp' BNFC'Position
data AddOp' a = Plus a | Minus a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type MulOp = MulOp' BNFC'Position
data MulOp' a = Times a | Div a | Mod a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type RelOp = RelOp' BNFC'Position
data RelOp' a = LTH a | LE a | GTH a | GE a | EQU a | NE a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    Prog p _ -> p

instance HasPosition TopDef where
  hasPosition = \case
    FnDef p _ _ _ _ -> p
    ClassDef p _ _ -> p
    ClassExt p _ _ _ -> p

instance HasPosition Field where
  hasPosition = \case
    AttrDef p _ _ -> p
    MethodDef p _ _ _ _ -> p

instance HasPosition Arg where
  hasPosition = \case
    Ar p _ _ -> p

instance HasPosition Stmt where
  hasPosition = \case
    Empty p -> p
    Exp p _ -> p
    Ass p _ _ -> p
    Incr p _ -> p
    Decr p _ -> p
    Ret p _ -> p
    VRet p -> p
    If p _ _ -> p
    IfElse p _ _ _ -> p
    While p _ _ -> p
    For p _ _ _ _ -> p
    BStmt p _ -> p
    Decl p _ _ -> p

instance HasPosition Block where
  hasPosition = \case
    Blck p _ -> p

instance HasPosition Item where
  hasPosition = \case
    NoInit p _ -> p
    Init p _ _ -> p

instance HasPosition Type where
  hasPosition = \case
    Int p -> p
    Str p -> p
    Bool p -> p
    Void p -> p
    Array p _ -> p
    Class p _ -> p

instance HasPosition Expr where
  hasPosition = \case
    EOr p _ _ -> p
    EAnd p _ _ -> p
    ERel p _ _ _ -> p
    EAdd p _ _ _ -> p
    EMul p _ _ _ -> p
    Not p _ -> p
    Neg p _ -> p
    EClass p _ -> p
    EAttr p _ _ -> p
    EMethod p _ _ _ -> p
    EArr p _ _ -> p
    EElem p _ _ -> p
    ESelf p -> p
    ENull p -> p
    ENullCast p _ -> p
    ENullClss p _ -> p
    EVar p _ -> p
    EInt p _ -> p
    EString p _ -> p
    ETrue p -> p
    EFalse p -> p
    EApp p _ _ -> p

instance HasPosition AddOp where
  hasPosition = \case
    Plus p -> p
    Minus p -> p

instance HasPosition MulOp where
  hasPosition = \case
    Times p -> p
    Div p -> p
    Mod p -> p

instance HasPosition RelOp where
  hasPosition = \case
    LTH p -> p
    LE p -> p
    GTH p -> p
    GE p -> p
    EQU p -> p
    NE p -> p

